# Generated by Django 4.1 on 2022-08-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="policy_agreement",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
