# Generated by Django 4.1 on 2022-08-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_customuser_managers_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
