version: "3.9"

services:

  backend:
    container_name: backend
    build: ./server
    ports:
      - "8000:8000"
    restart: always
    entrypoint: /entrypoint.sh
    volumes:
      - static_volume:/backend/staticfiles
    depends_on:
      - db
    command: ["./server/healthy-check.sh", "db:5432"]


  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: server/.env

  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/backend/staticfiles
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  static_volume:
  postgres_data:
