version: "3.9"

services:

  backend:
    container_name: backend
    build: ./server
#    ports:
#      - "8000:8000"
    restart: always
    entrypoint: /entrypoint.sh
    volumes:
      - ./server:/backend
      - static_volume:/backend/staticfiles
    depends_on:
      - db
    command: ["./server/healthy-check.sh", "db:5432"]


  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: server/.env
#    ports:
#      - 172.17.0.1:5432:5432
  redis:
    image: redis:alpine
  celery:
      restart: always
      build:
        context: ./server
      command: celery -A config.celery beat && celery -A config worker -l info
      volumes:
        - ./server:/backend
      env_file:
        - ./server/.env
      depends_on:
        - db
        - redis
        - backend
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/backend/staticfiles
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
  static_volume:
  postgres_data: