# Generated by Django 4.1 on 2022-08-21 08:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvertContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="номер телефона"
                    ),
                ),
            ],
            options={
                "verbose_name": "номер для объявления",
                "verbose_name_plural": "номера для объявлении",
            },
        ),
        migrations.CreateModel(
            name="AdvertImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="advert/images/%Y/%m/%d")),
            ],
            options={
                "verbose_name": "изображение для объявлении",
                "verbose_name_plural": "изображении для объявлении",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="category/icon/%Y/%m/%d",
                        verbose_name="изображение категории",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="название категории"),
                ),
                (
                    "advert_count",
                    models.IntegerField(verbose_name="количество объявлении"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="название города"),
                ),
            ],
            options={
                "verbose_name": "Города",
            },
        ),
        migrations.CreateModel(
            name="Promote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.ImageField(blank=True, upload_to="promote/%Y/%m/%d")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("vip", "VIP"),
                            ("urgently", "Срочно"),
                            ("highlighted", "выделенить"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Реклама",
                "verbose_name_plural": "Рекламы",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="название подкатегори"
                    ),
                ),
                (
                    "advert_count",
                    models.IntegerField(verbose_name="количество объявлении"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advert.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="название объявления"
                    ),
                ),
                ("from_price", models.IntegerField(verbose_name="от цены")),
                ("to_price", models.IntegerField(verbose_name="до цены")),
                ("description", models.TextField(verbose_name="описание")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="номер телефона"
                    ),
                ),
                (
                    "wa_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="WhatsApp номер"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "image_count",
                    models.IntegerField(verbose_name="количество изображений"),
                ),
                ("view", models.IntegerField(verbose_name="просмотры")),
                ("is_active", models.BooleanField()),
                ("is_verified", models.BooleanField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advert.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="advert.city",
                        verbose_name="город",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="advert.advertcontact",
                        verbose_name="доп номер телефона",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advert.advertimage",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "promote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="advert.promote",
                        verbose_name="реклама",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advert.subcategory",
                        verbose_name="подкатегория",
                    ),
                ),
            ],
            options={
                "verbose_name": "объявление",
                "verbose_name_plural": "объявлении",
            },
        ),
    ]
