# Generated by Django 4.1 on 2022-09-01 10:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название объявления')),
                ('description', models.TextField(verbose_name='описание')),
                ('start_price', models.IntegerField(verbose_name='от цены')),
                ('end_price', models.IntegerField(verbose_name='до цены')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('wa_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='WhatsApp номер')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('act', 'Активный'), ('inact', 'Неактивный'), ('on_r', 'На проверке')], default='on_r', max_length=10, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='category/icon/%Y/%m/%d', verbose_name='иконка категории')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
                ('advert_count', models.IntegerField(default=0, verbose_name='количество объявлений')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Promote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='promote/%Y/%m/%d')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='описание')),
                ('types', models.CharField(choices=[('vip', 'VIP'), ('urgently', 'Срочно'), ('highlighted', 'выделенить')], max_length=50)),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название подкатегори')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sub_category', to='advert.category', verbose_name='Под-категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advert/images/%Y/%m/%d')),
                ('advert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_image', to='advert.advert', verbose_name='объявления')),
            ],
            options={
                'verbose_name': 'изображение для объявления',
                'verbose_name_plural': 'изображения для объявления',
            },
        ),
        migrations.CreateModel(
            name='AdvertContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_contact', to='advert.advert', verbose_name='объявление')),
            ],
            options={
                'verbose_name': 'номер для объявления',
                'verbose_name_plural': 'номера для объявлении',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_advert', to='advert.category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='advert',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_product', to='advert.city', verbose_name='город'),
        ),
    ]
