# Generated by Django 4.1 on 2022-08-21 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("advert", "0002_alter_city_options_advert_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advert",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="advert",
            name="image",
        ),
        migrations.AddField(
            model_name="advertcontact",
            name="advert",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="advert.advert",
                verbose_name="объявления",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advertimage",
            name="advert",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="advert.advert",
                verbose_name="объявления",
            ),
            preserve_default=False,
        ),
    ]
