# Generated by Django 4.1 on 2022-09-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_advertview'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertview',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
