# Generated by Django 4.1 on 2022-08-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("advert", "0003_remove_advert_contact_remove_advert_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertimage",
            name="advert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advert_image",
                to="advert.advert",
                verbose_name="объявления",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="advert_count",
            field=models.IntegerField(default=0, verbose_name="количество объявлении"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="advert_count",
            field=models.IntegerField(default=0, verbose_name="количество объявлении"),
        ),
    ]
