# Generated by Django 4.1 on 2022-08-22 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "advert",
            "0004_alter_advertimage_advert_alter_category_advert_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertcontact",
            name="advert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advert_contact",
                to="advert.advert",
                verbose_name="объявления",
            ),
        ),
    ]
