# Generated by Django 4.1 on 2022-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_alter_advertcontact_advert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image_count',
            field=models.IntegerField(default=0, verbose_name='количество изображений'),
        ),
    ]
