# Generated by Django 4.1 on 2022-09-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_alter_advert_is_active_alter_advert_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertimage',
            old_name='advert',
            new_name='advert_id',
        ),
    ]
