# Generated by Django 4.1 on 2022-09-06 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advert", "0004_rename_advert_id_advertimage_advert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
                (
                    "date",
                    models.DateTimeField(auto_now=True, verbose_name="дата отправки"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="chat/files/%Y/%m/%d/",
                        verbose_name="файл",
                    ),
                ),
                (
                    "advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advert.advert",
                        verbose_name="объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщения",
                "verbose_name_plural": "Сообщение",
            },
        ),
    ]
