# Generated by Django 4.1 on 2022-08-28 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advert", "0007_alter_advert_is_active_alter_advert_is_verified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
                (
                    "date",
                    models.DateTimeField(auto_now=True, verbose_name="дата отправки"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="chat/files/%Y/%m/%d/",
                        verbose_name="файл",
                    ),
                ),
                (
                    "advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advert.advert",
                        verbose_name="объявление",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="отправитель",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщения",
                "verbose_name_plural": "Сообщение",
            },
        ),
    ]
