# Generated by Django 4.1 on 2022-09-06 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="отправитель",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="получатель",
            ),
        ),
    ]
