name: deploy
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy server
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: docker compose build --no-cache
    - run: docker compose up -d
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.ZEONMALL }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts


    - name: Deploy with rsync
      run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/group_b/Zmall
